database:
    database: shell_service_test
    user: shell_service
    host: localhost
    port: 5432

server:
    url: http://localhost:5000
    auth:
      debug_login: True
      google_oauth2_key:
      google_oauth2_secret:
